# pipeline de integração contínua utilizando GitHub Actions 

# nome da pipeline
name: 'Pipeline Integrada'

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch

on:
  workflow_dispatch:

  # Execução por push
  push:
    branches:
     - main
  
  schedule:
  # cronograma de execução
  # 1 - minutos, 2 - Hora, 3 - dia do mês, 4 - mês, 5 - dia da semana
  # Roda a cada 30 min
  - cron: '*/30 * * * *'

#tarefas dentro da pipeline = jobs

jobs:
  #nome do job
  tests:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest

    # passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalção do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # Instalando depêndencia
      - name: Instalar dependências
        run: npm ci

      # executar os testes 
      - name: Executando testes 
        run: npx mocha
